name: chafon_h103_rfid_example
description: Demonstrates how to use the chafon_h103_rfid plugin.
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  chafon_h103_rfid:
    path: ../
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.0
  hive_ce: ^2.8.0
  hive_ce_flutter: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.0

flutter:
  uses-material-design: true
