// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:chafon_h103_rfid_example/models/tag.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TagAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TagAdapter());
  }
}
